---
- name: ensure Auditd is installed
  package:
    name: auditd
    state: present

- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    filename: docker
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "xenial"

- name: Update apt-cache
  apt:
    update_cache: yes
    upgrade: no
    cache_valid_time: 7200

- name: Install docker-ce
  package:
    name: docker-ce
    state: latest
