---
#
# Copyright 2016 Travelex
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

- name: install Prerequisites
  include: install_prereqs.yml
  tags: prereqs

- name: Run Section 01
  include: section_01.yml
  tags: section1

- name: Run Section 02
  include: section_02.yml
  tags: section2

- name: Run Section 03
  include: section_03.yml
  tags: section3

- name: Run Section 04
  include: section_04.yml
  tags: section4

- name: Run Section 05
  include: section_05.yml
  tags: section5

- name: Run Section 06
  include: section_06.yml
  tags: section6
