---
- name: 1.1 Ensure a separate partition for containers has been created (Scored)
  debug: msg="*** This should be done by a separate playbook/process. Due to the ordering, this cannot be done during build-time"
  tags:
    - scored
    - section1
    - section1.1

- name: 1.2 Ensure the container host has been Hardened (Not Scored)
  debug: msg="*** This should be done by a separate playbook"
  tags:
   - notscored
   - section1
   - section1.2

- name: 1.3 Ensure Docker is up to date (Not Scored)
  package:
    name: docker-ce
    state: latest
  tags:
   - notscored
   - section1
   - section1.3
   - skip_ansible_lint

- name: 1.4 Ensure only trusted users are allowed to control Docker daemon (Scored)
  debug: msg="*** Not in a scope of this playbook"
  tags:
   - scored
   - section1
   - section1.4

- name: Create auditd rules
  template:
    backup: yes
    src: audit.rules
    dest: /etc/audit/rules.d/docker.rules
    owner: root
    group: root
    mode: 0640
  register: auditrules
  tags:
   - scored
   - section1
   - section1.5
   - section1.6
   - section1.7
   - section1.8
   - section1.9
   - section1.10
   - section1.11
   - section1.12
   - section1.13

- name: generate audit rules
  when: auditrules.changed # noqa 503
  command: augenrules

# auditd might be in immutable mode, restarting the service will have no effect - needs reboot
- name: reboot due to changed auditd rules
  when: auditrules.changed # noqa 503
  reboot:
    msg: post auditd restart
    post_reboot_delay: 10
    reboot_timeout: 300

# This forces handler to run
- meta: flush_handlers
  tags:
    - scored
    - section1
    - section1.5
    - section1.6
    - section1.7
    - section1.8
    - section1.9
    - section1.10
    - section1.11
    - section1.12
    - section1.13

- name: 1.5 Ensure auditing is configured for the Docker daemon (Scored)
  shell: auditctl -l | grep /usr/bin/docker # noqa 306
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  tags:
   - scored
   - section1
   - section1.5

- name: 1.6 Ensure auditing is configured for Docker files and directories - /var/lib/docker (Scored)
  shell: auditctl -l | grep /var/lib/docker # noqa 306
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  tags:
   - scored
   - section1
   - section1.6

- name: 1.7 Ensure auditing is configured for Docker files and directories - /etc/docker (Scored)
  shell: auditctl -l | grep /etc/docker # noqa 306
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  tags:
   - scored
   - section1
   - section1.7

- name: 1.8 Ensure auditing is configured for Docker files and directories - docker.service (Scored)
  shell: auditctl -l | grep /lib/systemd/system/docker.service # noqa 306
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  tags:
   - scored
   - section1
   - section1.8

- name: 1.9 Ensure auditing is configured for Docker files and directories - docker.socket (Scored)
  shell: auditctl -l | grep /lib/systemd/system/docker.socket # noqa 306
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  tags:
   - scored
   - section1
   - section1.9

- name: 1.10 Ensure auditing is configured for Docker files and directories - /etc/default/docker (Scored)
  shell: auditctl -l | grep /etc/default/docker # noqa 306
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  tags:
   - scored
   - section1
   - section1.10

- name: 1.11 Ensure auditing is configured for Docker files and directories - /etc/docker/daemon.json (Scored)
  shell: auditctl -l | grep /etc/docker/daemon.json # noqa 306
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  tags:
   - scored
   - section1
   - section1.11

- name: 1.12 Ensure auditing is configured for Docker files and directories - /usr/bin/docker-containerd (Scored)
  shell: auditctl -l | grep /usr/bin/docker-containerd # noqa 306
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  tags:
   - scored
   - section1
   - section1.12

- name: 1.13 Ensure auditing is configured for Docker files and directories - /usr/bin/docker-runc (Scored)
  shell: auditctl -l | grep /usr/bin/docker-runc # noqa 306
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  tags:
   - scored
   - section1
   - section1.13
