---
- name: 1.1 Create a separate partition for containers (Scored)
  command: "grep /var/lib/docker /etc/fstab"
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section1.1

- name: Fail when file does not exist
  fail: msg="fstab No such file or directory"
  when: "'grep: fstab: No such file or directory' in res.stderr"
  tags:
   - scored
   - section1.1

- name: 1.2 Use the updated Linux Kernel (Scored)
  shell: uname -r | grep ^3\.10
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section1.2

- name: 1.3 Harden the container host (Not Scored)
  debug: msg="*** This should be done by a separate playbook"
  tags:
   - notscored
   - section1.3

- name: 1.4 Remove all non-essential services from the host (Not Scored)
  debug: msg="*** Not in a scope of this playbook"
  tags:
   - notscored
   - section1.4

- name: 1.5 Keep Docker up to date (Not Scored)
  package:
    name: docker-engine 
    state: latest
  tags:
   - notscored
   - section1.5

- name: 1.6 Only allow trusted users to control Docker daemon (Scored)
  debug: msg="*** Not in a scope of this playbook"
  tags:
   - scored
   - section1.6

- name: 1.7 Audit docker daemon (Scored)
  lineinfile: 
    dest: /etc/audit/audit.rules
    line: "-w /usr/bin/docker -k docker"
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.7

- name: 1.8 Audit Docker files and directories - /var/lib/docker (Scored)
  lineinfile: 
    dest: /etc/audit/audit.rules
    line: "-w /var/lib/docker -k docker"
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.8

- name: 1.9 Audit Docker files and directories - /etc/docker (Scored)
  lineinfile: 
    dest: /etc/audit/audit.rules
    line: "-w /etc/docker -k docker"
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.9

- name: 1.10 Audit Docker files and directories - docker.service (Scored)
  lineinfile: 
    dest: /etc/audit/audit.rules
    line: "-w /usr/lib/systemd/system/docker.service -k docker"
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.10

- name: 1.11 Audit Docker files and directories - docker.socket (Scored)
  lineinfile: 
    dest: /etc/audit/audit.rules
    line: "-w /usr/lib/systemd/system/docker.socket -k docker"
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.11

- name: 1.12 Audit Docker files and directories - /etc/default/docker (Scored)
  lineinfile: 
    dest: /etc/audit/audit.rules
    line: "-w /etc/default/docker -k docker"
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.12

- name: 1.13 Audit Docker files and directories - /etc/docker/daemon.json (Scored)
  lineinfile: 
    dest: /etc/audit/audit.rules
    line: "-w /etc/docker/daemon.json -k docker"
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.13

- name: 1.14 Audit Docker files and directories - /usr/bin/docker-containerd (Scored)
  lineinfile: 
    dest: /etc/audit/audit.rules
    line: "-w /usr/bin/docker-containerd -k docker"
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.14

- name: 1.15 Audit Docker files and directories - /usr/bin/docker-runc (Scored)
  lineinfile: 
    dest: /etc/audit/audit.rules
    line: "-w /usr/bin/docker-runc -k docker"
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.15
