---
version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install ansible==2.8.0 ansible-lint==4.1.0
      - run:
          command: |
            . venv/bin/activate
            ansible-lint .
