# https://bugzilla.redhat.com/show_bug.cgi?id=1026648
  - name: Reload auditd Rules
    service:
      name: auditd
      state: restarted

  - name: Reload docker
    service:
      name: docker
      state: restarted
